version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./privik.db
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - privik-network

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - privik-network

  # Redis Cache Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - privik-network

  # PostgreSQL Database (Optional - for production)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=privik
      - POSTGRES_USER=privik
      - POSTGRES_PASSWORD=privik123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - privik-network
    profiles:
      - production

volumes:
  backend_data:
  redis_data:
  postgres_data:

networks:
  privik-network:
    driver: bridge